version: '3.7'

services:
  influxdb:
    image: influxdb:2.0
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB_INIT_MODE=setup
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=adminpassword
      - INFLUXDB_HTTP_AUTH_ENABLED=true
      - INFLUXDB_ORG=dbsense
      - INFLUXDB_BUCKET=sound_bucket
    volumes:
      - influxdb_data:/var/lib/influxdb2

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - influxdb

  yamnet:
    build: .
    container_name: yamnet
    devices:
      - "/dev/snd:/dev/snd"
    privileged: true
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_TOKEN="T6lW1p5i8FWe_eZkbB3FuwKLqA_3I5NsTuYN0G3ecDeuEoAf-0cH7HllioCvi6f4zZzl-PGIJLI3UbyoYitP0w=="
      - INFLUXDB_ORG=dbsense
      - INFLUXDB_BUCKET=sound_bucket
      - ALSADEV=default  # Configuration ALSA critique
      - PULSE_SERVER=unix:/run/user/1002/pulse/native
    volumes:     
      - /run/user/1002/pulse:/run/user/1002/pulse/native
      - ${XDG_RUNTIME_DIR}/pulse/native:/run/user/1002/pulse/native
     # - ~/.config/pulse/cookie:/root/.config/pulse/cookie
      - ./main.py:/app/main.py
    stdin_open: true
    tty: true
    depends_on:
      - influxdb

    

volumes:
  influxdb_data:
  grafana_data:
