# .github/workflows/docker-deploy.yml
name: Build & Push Docker Image

on:
  push:
    branches:
      - main  # ou master si c'est ta branche principale

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: ./app4
          push: true
          tags: alidbsense/dbsense:latest
